# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='用户名')),
                ('mobile', models.CharField(blank=True, max_length=16, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='电子邮箱')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='')),
                ('wx_openid', models.CharField(blank=True, max_length=128, verbose_name='微信 OpenID')),
                ('password_hash', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('account_state', models.SmallIntegerField(choices=[(-1, '冻结'), (0, '未激活'), (1, '已激活')], default=0, verbose_name='账户状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
