# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号码')),
                ('code', models.CharField(max_length=16, verbose_name='验证码')),
                ('context', models.CharField(max_length=32, verbose_name='使用场景')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
            },
        ),
    ]
