# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170616_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='remote_ip',
            field=models.CharField(blank=True, max_length=32, verbose_name='IP 地址'),
        ),
    ]
