# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_smscode_remote_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='context',
            field=models.CharField(choices=[('login', '登录'), ('register', '注册'), ('forget', '忘记'), ('transfer', '转移')], default='login', max_length=32, verbose_name='使用场景'),
        ),
    ]
