# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170726_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoogle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google', to='api.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userweixin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weixin', to='api.User', verbose_name='用户'),
        ),
    ]
