# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_weixinapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('totp', 'TOTP'), ('hotp', 'HOTP')], default='totp', max_length=16, verbose_name='类型')),
                ('secret', models.CharField(max_length=128, verbose_name='密钥')),
                ('bind_time', models.DateTimeField(blank=True, null=True, verbose_name='绑定时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='api.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '动态密码',
                'verbose_name_plural': '动态密码',
            },
        ),
    ]
