# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weixinapp',
            options={'verbose_name': '微信应用程序', 'verbose_name_plural': '微信应用程序'},
        ),
        migrations.AddField(
            model_name='weixinapp',
            name='sort',
            field=models.CharField(choices=[('biz', '公众号/小程序'), ('web', '网站应用'), ('mobile', '公众号/小程序')], default='biz', max_length=16),
        ),
    ]
