# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170907_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweixin',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256, verbose_name='Refresh Token'),
        ),
    ]
