# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userweixin_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinapp',
            name='sort',
            field=models.CharField(choices=[('biz', '公众号/小程序'), ('web', '网站应用'), ('mobile', '移动应用')], default='biz', max_length=16),
        ),
    ]
