# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170915_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('biz', '公众号/小程序'), ('web', '网站应用'), ('mobile', '移动应用')], default='biz', max_length=16)),
                ('openid', models.CharField(blank=True, max_length=128, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, max_length=128, verbose_name='UnionID')),
                ('access_token', models.CharField(blank=True, max_length=256)),
                ('expires_time', models.DateTimeField(blank=True, null=True)),
                ('detail_raw', models.CharField(blank=True, max_length=512, verbose_name='详情原始文本')),
            ],
            options={
                'verbose_name': '微信应用用户账号',
                'verbose_name_plural': '微信应用用户账号',
            },
        ),
    ]
